//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkPortal.RegistrationReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrationReference.RegistrationServiceSoap")]
    public interface RegistrationServiceSoap {
        
        // CODEGEN: Generating message contract since element name firstName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        NetworkPortal.RegistrationReference.RegisterUserResponse RegisterUser(NetworkPortal.RegistrationReference.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.RegisterUserResponse> RegisterUserAsync(NetworkPortal.RegistrationReference.RegisterUserRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatus", ReplyAction="*")]
        NetworkPortal.RegistrationReference.GetStatusResponse GetStatus(NetworkPortal.RegistrationReference.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetStatusResponse> GetStatusAsync(NetworkPortal.RegistrationReference.GetStatusRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        NetworkPortal.RegistrationReference.LoginResponse Login(NetworkPortal.RegistrationReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.LoginResponse> LoginAsync(NetworkPortal.RegistrationReference.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        NetworkPortal.RegistrationReference.GetAllUsersResponse GetAllUsers(NetworkPortal.RegistrationReference.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetAllUsersResponse> GetAllUsersAsync(NetworkPortal.RegistrationReference.GetAllUsersRequest request);
        
        // CODEGEN: Generating message contract since element name fromEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendFriendRequest", ReplyAction="*")]
        NetworkPortal.RegistrationReference.SendFriendRequestResponse SendFriendRequest(NetworkPortal.RegistrationReference.SendFriendRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendFriendRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.SendFriendRequestResponse> SendFriendRequestAsync(NetworkPortal.RegistrationReference.SendFriendRequestRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFriends", ReplyAction="*")]
        NetworkPortal.RegistrationReference.GetFriendsResponse GetFriends(NetworkPortal.RegistrationReference.GetFriendsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFriends", ReplyAction="*")]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetFriendsResponse> GetFriendsAsync(NetworkPortal.RegistrationReference.GetFriendsRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveInterests", ReplyAction="*")]
        NetworkPortal.RegistrationReference.SaveInterestsResponse SaveInterests(NetworkPortal.RegistrationReference.SaveInterestsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveInterests", ReplyAction="*")]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.SaveInterestsResponse> SaveInterestsAsync(NetworkPortal.RegistrationReference.SaveInterestsRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        NetworkPortal.RegistrationReference.GetMessagesResponse GetMessages(NetworkPortal.RegistrationReference.GetMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetMessagesResponse> GetMessagesAsync(NetworkPortal.RegistrationReference.GetMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name fromEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        NetworkPortal.RegistrationReference.SendMessageResponse SendMessage(NetworkPortal.RegistrationReference.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.SendMessageResponse> SendMessageAsync(NetworkPortal.RegistrationReference.SendMessageRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllNetworksResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllNetworks", ReplyAction="*")]
        NetworkPortal.RegistrationReference.GetAllNetworksResponse GetAllNetworks(NetworkPortal.RegistrationReference.GetAllNetworksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllNetworks", ReplyAction="*")]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetAllNetworksResponse> GetAllNetworksAsync(NetworkPortal.RegistrationReference.GetAllNetworksRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserNetworks", ReplyAction="*")]
        NetworkPortal.RegistrationReference.GetUserNetworksResponse GetUserNetworks(NetworkPortal.RegistrationReference.GetUserNetworksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserNetworks", ReplyAction="*")]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetUserNetworksResponse> GetUserNetworksAsync(NetworkPortal.RegistrationReference.GetUserNetworksRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JoinNetwork", ReplyAction="*")]
        NetworkPortal.RegistrationReference.JoinNetworkResponse JoinNetwork(NetworkPortal.RegistrationReference.JoinNetworkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JoinNetwork", ReplyAction="*")]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.JoinNetworkResponse> JoinNetworkAsync(NetworkPortal.RegistrationReference.JoinNetworkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUser", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.RegisterUserRequestBody Body;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(NetworkPortal.RegistrationReference.RegisterUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string confirmPassword;
        
        public RegisterUserRequestBody() {
        }
        
        public RegisterUserRequestBody(string firstName, string lastName, string email, System.DateTime dob, string password, string confirmPassword) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.email = email;
            this.dob = dob;
            this.password = password;
            this.confirmPassword = confirmPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.RegisterUserResponseBody Body;
        
        public RegisterUserResponse() {
        }
        
        public RegisterUserResponse(NetworkPortal.RegistrationReference.RegisterUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterUserResult;
        
        public RegisterUserResponseBody() {
        }
        
        public RegisterUserResponseBody(string RegisterUserResult) {
            this.RegisterUserResult = RegisterUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatus", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.GetStatusRequestBody Body;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(NetworkPortal.RegistrationReference.GetStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetStatusRequestBody() {
        }
        
        public GetStatusRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.GetStatusResponseBody Body;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(NetworkPortal.RegistrationReference.GetStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStatusResult;
        
        public GetStatusResponseBody() {
        }
        
        public GetStatusResponseBody(string GetStatusResult) {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(NetworkPortal.RegistrationReference.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(NetworkPortal.RegistrationReference.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsers", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.GetAllUsersRequestBody Body;
        
        public GetAllUsersRequest() {
        }
        
        public GetAllUsersRequest(NetworkPortal.RegistrationReference.GetAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUsersRequestBody {
        
        public GetAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.GetAllUsersResponseBody Body;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(NetworkPortal.RegistrationReference.GetAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetworkPortal.RegistrationReference.ArrayOfString GetAllUsersResult;
        
        public GetAllUsersResponseBody() {
        }
        
        public GetAllUsersResponseBody(NetworkPortal.RegistrationReference.ArrayOfString GetAllUsersResult) {
            this.GetAllUsersResult = GetAllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFriendRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFriendRequest", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.SendFriendRequestRequestBody Body;
        
        public SendFriendRequestRequest() {
        }
        
        public SendFriendRequestRequest(NetworkPortal.RegistrationReference.SendFriendRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendFriendRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toEmail;
        
        public SendFriendRequestRequestBody() {
        }
        
        public SendFriendRequestRequestBody(string fromEmail, string toEmail) {
            this.fromEmail = fromEmail;
            this.toEmail = toEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFriendRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFriendRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.SendFriendRequestResponseBody Body;
        
        public SendFriendRequestResponse() {
        }
        
        public SendFriendRequestResponse(NetworkPortal.RegistrationReference.SendFriendRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendFriendRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendFriendRequestResult;
        
        public SendFriendRequestResponseBody() {
        }
        
        public SendFriendRequestResponseBody(string SendFriendRequestResult) {
            this.SendFriendRequestResult = SendFriendRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFriendsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFriends", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.GetFriendsRequestBody Body;
        
        public GetFriendsRequest() {
        }
        
        public GetFriendsRequest(NetworkPortal.RegistrationReference.GetFriendsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFriendsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetFriendsRequestBody() {
        }
        
        public GetFriendsRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFriendsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFriendsResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.GetFriendsResponseBody Body;
        
        public GetFriendsResponse() {
        }
        
        public GetFriendsResponse(NetworkPortal.RegistrationReference.GetFriendsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFriendsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetworkPortal.RegistrationReference.ArrayOfString GetFriendsResult;
        
        public GetFriendsResponseBody() {
        }
        
        public GetFriendsResponseBody(NetworkPortal.RegistrationReference.ArrayOfString GetFriendsResult) {
            this.GetFriendsResult = GetFriendsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveInterestsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveInterests", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.SaveInterestsRequestBody Body;
        
        public SaveInterestsRequest() {
        }
        
        public SaveInterestsRequest(NetworkPortal.RegistrationReference.SaveInterestsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveInterestsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string interests;
        
        public SaveInterestsRequestBody() {
        }
        
        public SaveInterestsRequestBody(string email, string interests) {
            this.email = email;
            this.interests = interests;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveInterestsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveInterestsResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.SaveInterestsResponseBody Body;
        
        public SaveInterestsResponse() {
        }
        
        public SaveInterestsResponse(NetworkPortal.RegistrationReference.SaveInterestsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveInterestsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveInterestsResult;
        
        public SaveInterestsResponseBody() {
        }
        
        public SaveInterestsResponseBody(string SaveInterestsResult) {
            this.SaveInterestsResult = SaveInterestsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.GetMessagesRequestBody Body;
        
        public GetMessagesRequest() {
        }
        
        public GetMessagesRequest(NetworkPortal.RegistrationReference.GetMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetMessagesRequestBody() {
        }
        
        public GetMessagesRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.GetMessagesResponseBody Body;
        
        public GetMessagesResponse() {
        }
        
        public GetMessagesResponse(NetworkPortal.RegistrationReference.GetMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetworkPortal.RegistrationReference.ArrayOfString GetMessagesResult;
        
        public GetMessagesResponseBody() {
        }
        
        public GetMessagesResponseBody(NetworkPortal.RegistrationReference.ArrayOfString GetMessagesResult) {
            this.GetMessagesResult = GetMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(NetworkPortal.RegistrationReference.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string fromEmail, string toEmail, string message) {
            this.fromEmail = fromEmail;
            this.toEmail = toEmail;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(NetworkPortal.RegistrationReference.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(string SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllNetworksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllNetworks", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.GetAllNetworksRequestBody Body;
        
        public GetAllNetworksRequest() {
        }
        
        public GetAllNetworksRequest(NetworkPortal.RegistrationReference.GetAllNetworksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllNetworksRequestBody {
        
        public GetAllNetworksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllNetworksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllNetworksResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.GetAllNetworksResponseBody Body;
        
        public GetAllNetworksResponse() {
        }
        
        public GetAllNetworksResponse(NetworkPortal.RegistrationReference.GetAllNetworksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllNetworksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetworkPortal.RegistrationReference.ArrayOfString GetAllNetworksResult;
        
        public GetAllNetworksResponseBody() {
        }
        
        public GetAllNetworksResponseBody(NetworkPortal.RegistrationReference.ArrayOfString GetAllNetworksResult) {
            this.GetAllNetworksResult = GetAllNetworksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNetworksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNetworks", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.GetUserNetworksRequestBody Body;
        
        public GetUserNetworksRequest() {
        }
        
        public GetUserNetworksRequest(NetworkPortal.RegistrationReference.GetUserNetworksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNetworksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetUserNetworksRequestBody() {
        }
        
        public GetUserNetworksRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNetworksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNetworksResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.GetUserNetworksResponseBody Body;
        
        public GetUserNetworksResponse() {
        }
        
        public GetUserNetworksResponse(NetworkPortal.RegistrationReference.GetUserNetworksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNetworksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetworkPortal.RegistrationReference.ArrayOfString GetUserNetworksResult;
        
        public GetUserNetworksResponseBody() {
        }
        
        public GetUserNetworksResponseBody(NetworkPortal.RegistrationReference.ArrayOfString GetUserNetworksResult) {
            this.GetUserNetworksResult = GetUserNetworksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JoinNetworkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JoinNetwork", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.JoinNetworkRequestBody Body;
        
        public JoinNetworkRequest() {
        }
        
        public JoinNetworkRequest(NetworkPortal.RegistrationReference.JoinNetworkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JoinNetworkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int networkId;
        
        public JoinNetworkRequestBody() {
        }
        
        public JoinNetworkRequestBody(string email, int networkId) {
            this.email = email;
            this.networkId = networkId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JoinNetworkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JoinNetworkResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetworkPortal.RegistrationReference.JoinNetworkResponseBody Body;
        
        public JoinNetworkResponse() {
        }
        
        public JoinNetworkResponse(NetworkPortal.RegistrationReference.JoinNetworkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JoinNetworkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JoinNetworkResult;
        
        public JoinNetworkResponseBody() {
        }
        
        public JoinNetworkResponseBody(string JoinNetworkResult) {
            this.JoinNetworkResult = JoinNetworkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrationServiceSoapChannel : NetworkPortal.RegistrationReference.RegistrationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationServiceSoapClient : System.ServiceModel.ClientBase<NetworkPortal.RegistrationReference.RegistrationServiceSoap>, NetworkPortal.RegistrationReference.RegistrationServiceSoap {
        
        public RegistrationServiceSoapClient() {
        }
        
        public RegistrationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetworkPortal.RegistrationReference.RegisterUserResponse NetworkPortal.RegistrationReference.RegistrationServiceSoap.RegisterUser(NetworkPortal.RegistrationReference.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public string RegisterUser(string firstName, string lastName, string email, System.DateTime dob, string password, string confirmPassword) {
            NetworkPortal.RegistrationReference.RegisterUserRequest inValue = new NetworkPortal.RegistrationReference.RegisterUserRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.RegisterUserRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.email = email;
            inValue.Body.dob = dob;
            inValue.Body.password = password;
            inValue.Body.confirmPassword = confirmPassword;
            NetworkPortal.RegistrationReference.RegisterUserResponse retVal = ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).RegisterUser(inValue);
            return retVal.Body.RegisterUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.RegisterUserResponse> NetworkPortal.RegistrationReference.RegistrationServiceSoap.RegisterUserAsync(NetworkPortal.RegistrationReference.RegisterUserRequest request) {
            return base.Channel.RegisterUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.RegisterUserResponse> RegisterUserAsync(string firstName, string lastName, string email, System.DateTime dob, string password, string confirmPassword) {
            NetworkPortal.RegistrationReference.RegisterUserRequest inValue = new NetworkPortal.RegistrationReference.RegisterUserRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.RegisterUserRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.email = email;
            inValue.Body.dob = dob;
            inValue.Body.password = password;
            inValue.Body.confirmPassword = confirmPassword;
            return ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).RegisterUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetworkPortal.RegistrationReference.GetStatusResponse NetworkPortal.RegistrationReference.RegistrationServiceSoap.GetStatus(NetworkPortal.RegistrationReference.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public string GetStatus(string email) {
            NetworkPortal.RegistrationReference.GetStatusRequest inValue = new NetworkPortal.RegistrationReference.GetStatusRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.GetStatusRequestBody();
            inValue.Body.email = email;
            NetworkPortal.RegistrationReference.GetStatusResponse retVal = ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).GetStatus(inValue);
            return retVal.Body.GetStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetStatusResponse> NetworkPortal.RegistrationReference.RegistrationServiceSoap.GetStatusAsync(NetworkPortal.RegistrationReference.GetStatusRequest request) {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetStatusResponse> GetStatusAsync(string email) {
            NetworkPortal.RegistrationReference.GetStatusRequest inValue = new NetworkPortal.RegistrationReference.GetStatusRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.GetStatusRequestBody();
            inValue.Body.email = email;
            return ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).GetStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetworkPortal.RegistrationReference.LoginResponse NetworkPortal.RegistrationReference.RegistrationServiceSoap.Login(NetworkPortal.RegistrationReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string email, string password) {
            NetworkPortal.RegistrationReference.LoginRequest inValue = new NetworkPortal.RegistrationReference.LoginRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            NetworkPortal.RegistrationReference.LoginResponse retVal = ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.LoginResponse> NetworkPortal.RegistrationReference.RegistrationServiceSoap.LoginAsync(NetworkPortal.RegistrationReference.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.LoginResponse> LoginAsync(string email, string password) {
            NetworkPortal.RegistrationReference.LoginRequest inValue = new NetworkPortal.RegistrationReference.LoginRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetworkPortal.RegistrationReference.GetAllUsersResponse NetworkPortal.RegistrationReference.RegistrationServiceSoap.GetAllUsers(NetworkPortal.RegistrationReference.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public NetworkPortal.RegistrationReference.ArrayOfString GetAllUsers() {
            NetworkPortal.RegistrationReference.GetAllUsersRequest inValue = new NetworkPortal.RegistrationReference.GetAllUsersRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.GetAllUsersRequestBody();
            NetworkPortal.RegistrationReference.GetAllUsersResponse retVal = ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).GetAllUsers(inValue);
            return retVal.Body.GetAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetAllUsersResponse> NetworkPortal.RegistrationReference.RegistrationServiceSoap.GetAllUsersAsync(NetworkPortal.RegistrationReference.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetAllUsersResponse> GetAllUsersAsync() {
            NetworkPortal.RegistrationReference.GetAllUsersRequest inValue = new NetworkPortal.RegistrationReference.GetAllUsersRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.GetAllUsersRequestBody();
            return ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).GetAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetworkPortal.RegistrationReference.SendFriendRequestResponse NetworkPortal.RegistrationReference.RegistrationServiceSoap.SendFriendRequest(NetworkPortal.RegistrationReference.SendFriendRequestRequest request) {
            return base.Channel.SendFriendRequest(request);
        }
        
        public string SendFriendRequest(string fromEmail, string toEmail) {
            NetworkPortal.RegistrationReference.SendFriendRequestRequest inValue = new NetworkPortal.RegistrationReference.SendFriendRequestRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.SendFriendRequestRequestBody();
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.toEmail = toEmail;
            NetworkPortal.RegistrationReference.SendFriendRequestResponse retVal = ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).SendFriendRequest(inValue);
            return retVal.Body.SendFriendRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.SendFriendRequestResponse> NetworkPortal.RegistrationReference.RegistrationServiceSoap.SendFriendRequestAsync(NetworkPortal.RegistrationReference.SendFriendRequestRequest request) {
            return base.Channel.SendFriendRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.SendFriendRequestResponse> SendFriendRequestAsync(string fromEmail, string toEmail) {
            NetworkPortal.RegistrationReference.SendFriendRequestRequest inValue = new NetworkPortal.RegistrationReference.SendFriendRequestRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.SendFriendRequestRequestBody();
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.toEmail = toEmail;
            return ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).SendFriendRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetworkPortal.RegistrationReference.GetFriendsResponse NetworkPortal.RegistrationReference.RegistrationServiceSoap.GetFriends(NetworkPortal.RegistrationReference.GetFriendsRequest request) {
            return base.Channel.GetFriends(request);
        }
        
        public NetworkPortal.RegistrationReference.ArrayOfString GetFriends(string email) {
            NetworkPortal.RegistrationReference.GetFriendsRequest inValue = new NetworkPortal.RegistrationReference.GetFriendsRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.GetFriendsRequestBody();
            inValue.Body.email = email;
            NetworkPortal.RegistrationReference.GetFriendsResponse retVal = ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).GetFriends(inValue);
            return retVal.Body.GetFriendsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetFriendsResponse> NetworkPortal.RegistrationReference.RegistrationServiceSoap.GetFriendsAsync(NetworkPortal.RegistrationReference.GetFriendsRequest request) {
            return base.Channel.GetFriendsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetFriendsResponse> GetFriendsAsync(string email) {
            NetworkPortal.RegistrationReference.GetFriendsRequest inValue = new NetworkPortal.RegistrationReference.GetFriendsRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.GetFriendsRequestBody();
            inValue.Body.email = email;
            return ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).GetFriendsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetworkPortal.RegistrationReference.SaveInterestsResponse NetworkPortal.RegistrationReference.RegistrationServiceSoap.SaveInterests(NetworkPortal.RegistrationReference.SaveInterestsRequest request) {
            return base.Channel.SaveInterests(request);
        }
        
        public string SaveInterests(string email, string interests) {
            NetworkPortal.RegistrationReference.SaveInterestsRequest inValue = new NetworkPortal.RegistrationReference.SaveInterestsRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.SaveInterestsRequestBody();
            inValue.Body.email = email;
            inValue.Body.interests = interests;
            NetworkPortal.RegistrationReference.SaveInterestsResponse retVal = ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).SaveInterests(inValue);
            return retVal.Body.SaveInterestsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.SaveInterestsResponse> NetworkPortal.RegistrationReference.RegistrationServiceSoap.SaveInterestsAsync(NetworkPortal.RegistrationReference.SaveInterestsRequest request) {
            return base.Channel.SaveInterestsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.SaveInterestsResponse> SaveInterestsAsync(string email, string interests) {
            NetworkPortal.RegistrationReference.SaveInterestsRequest inValue = new NetworkPortal.RegistrationReference.SaveInterestsRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.SaveInterestsRequestBody();
            inValue.Body.email = email;
            inValue.Body.interests = interests;
            return ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).SaveInterestsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetworkPortal.RegistrationReference.GetMessagesResponse NetworkPortal.RegistrationReference.RegistrationServiceSoap.GetMessages(NetworkPortal.RegistrationReference.GetMessagesRequest request) {
            return base.Channel.GetMessages(request);
        }
        
        public NetworkPortal.RegistrationReference.ArrayOfString GetMessages(string email) {
            NetworkPortal.RegistrationReference.GetMessagesRequest inValue = new NetworkPortal.RegistrationReference.GetMessagesRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.GetMessagesRequestBody();
            inValue.Body.email = email;
            NetworkPortal.RegistrationReference.GetMessagesResponse retVal = ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).GetMessages(inValue);
            return retVal.Body.GetMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetMessagesResponse> NetworkPortal.RegistrationReference.RegistrationServiceSoap.GetMessagesAsync(NetworkPortal.RegistrationReference.GetMessagesRequest request) {
            return base.Channel.GetMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetMessagesResponse> GetMessagesAsync(string email) {
            NetworkPortal.RegistrationReference.GetMessagesRequest inValue = new NetworkPortal.RegistrationReference.GetMessagesRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.GetMessagesRequestBody();
            inValue.Body.email = email;
            return ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).GetMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetworkPortal.RegistrationReference.SendMessageResponse NetworkPortal.RegistrationReference.RegistrationServiceSoap.SendMessage(NetworkPortal.RegistrationReference.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public string SendMessage(string fromEmail, string toEmail, string message) {
            NetworkPortal.RegistrationReference.SendMessageRequest inValue = new NetworkPortal.RegistrationReference.SendMessageRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.SendMessageRequestBody();
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.toEmail = toEmail;
            inValue.Body.message = message;
            NetworkPortal.RegistrationReference.SendMessageResponse retVal = ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.SendMessageResponse> NetworkPortal.RegistrationReference.RegistrationServiceSoap.SendMessageAsync(NetworkPortal.RegistrationReference.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.SendMessageResponse> SendMessageAsync(string fromEmail, string toEmail, string message) {
            NetworkPortal.RegistrationReference.SendMessageRequest inValue = new NetworkPortal.RegistrationReference.SendMessageRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.SendMessageRequestBody();
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.toEmail = toEmail;
            inValue.Body.message = message;
            return ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetworkPortal.RegistrationReference.GetAllNetworksResponse NetworkPortal.RegistrationReference.RegistrationServiceSoap.GetAllNetworks(NetworkPortal.RegistrationReference.GetAllNetworksRequest request) {
            return base.Channel.GetAllNetworks(request);
        }
        
        public NetworkPortal.RegistrationReference.ArrayOfString GetAllNetworks() {
            NetworkPortal.RegistrationReference.GetAllNetworksRequest inValue = new NetworkPortal.RegistrationReference.GetAllNetworksRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.GetAllNetworksRequestBody();
            NetworkPortal.RegistrationReference.GetAllNetworksResponse retVal = ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).GetAllNetworks(inValue);
            return retVal.Body.GetAllNetworksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetAllNetworksResponse> NetworkPortal.RegistrationReference.RegistrationServiceSoap.GetAllNetworksAsync(NetworkPortal.RegistrationReference.GetAllNetworksRequest request) {
            return base.Channel.GetAllNetworksAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetAllNetworksResponse> GetAllNetworksAsync() {
            NetworkPortal.RegistrationReference.GetAllNetworksRequest inValue = new NetworkPortal.RegistrationReference.GetAllNetworksRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.GetAllNetworksRequestBody();
            return ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).GetAllNetworksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetworkPortal.RegistrationReference.GetUserNetworksResponse NetworkPortal.RegistrationReference.RegistrationServiceSoap.GetUserNetworks(NetworkPortal.RegistrationReference.GetUserNetworksRequest request) {
            return base.Channel.GetUserNetworks(request);
        }
        
        public NetworkPortal.RegistrationReference.ArrayOfString GetUserNetworks(string email) {
            NetworkPortal.RegistrationReference.GetUserNetworksRequest inValue = new NetworkPortal.RegistrationReference.GetUserNetworksRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.GetUserNetworksRequestBody();
            inValue.Body.email = email;
            NetworkPortal.RegistrationReference.GetUserNetworksResponse retVal = ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).GetUserNetworks(inValue);
            return retVal.Body.GetUserNetworksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetUserNetworksResponse> NetworkPortal.RegistrationReference.RegistrationServiceSoap.GetUserNetworksAsync(NetworkPortal.RegistrationReference.GetUserNetworksRequest request) {
            return base.Channel.GetUserNetworksAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.GetUserNetworksResponse> GetUserNetworksAsync(string email) {
            NetworkPortal.RegistrationReference.GetUserNetworksRequest inValue = new NetworkPortal.RegistrationReference.GetUserNetworksRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.GetUserNetworksRequestBody();
            inValue.Body.email = email;
            return ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).GetUserNetworksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetworkPortal.RegistrationReference.JoinNetworkResponse NetworkPortal.RegistrationReference.RegistrationServiceSoap.JoinNetwork(NetworkPortal.RegistrationReference.JoinNetworkRequest request) {
            return base.Channel.JoinNetwork(request);
        }
        
        public string JoinNetwork(string email, int networkId) {
            NetworkPortal.RegistrationReference.JoinNetworkRequest inValue = new NetworkPortal.RegistrationReference.JoinNetworkRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.JoinNetworkRequestBody();
            inValue.Body.email = email;
            inValue.Body.networkId = networkId;
            NetworkPortal.RegistrationReference.JoinNetworkResponse retVal = ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).JoinNetwork(inValue);
            return retVal.Body.JoinNetworkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.JoinNetworkResponse> NetworkPortal.RegistrationReference.RegistrationServiceSoap.JoinNetworkAsync(NetworkPortal.RegistrationReference.JoinNetworkRequest request) {
            return base.Channel.JoinNetworkAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetworkPortal.RegistrationReference.JoinNetworkResponse> JoinNetworkAsync(string email, int networkId) {
            NetworkPortal.RegistrationReference.JoinNetworkRequest inValue = new NetworkPortal.RegistrationReference.JoinNetworkRequest();
            inValue.Body = new NetworkPortal.RegistrationReference.JoinNetworkRequestBody();
            inValue.Body.email = email;
            inValue.Body.networkId = networkId;
            return ((NetworkPortal.RegistrationReference.RegistrationServiceSoap)(this)).JoinNetworkAsync(inValue);
        }
    }
}
